"""Build the medicine-mode drug-name database from the CDSCO's NLEM 2022.

    python data/scripts/build_drug_db.py            # download, parse, write the .txt
    python data/scripts/build_drug_db.py --check    # verify the committed file is current

Why NLEM and not a brand list
-----------------------------
`DEC-007` says a drug name is reported only if it matches a *verified* database, because a
VLM will otherwise invent one. That only means something if the database itself traces to an
authority. The National List of Essential Medicines 2022, published by the Ministry of Health
via CDSCO, is government-issued, dated, and citable in the report.

It contains generic names only, and that is the right key to match on: Indian labelling rules
require the generic name on the pack (the Paracip strip prints "PARACETAMOL TABLETS IP" under
the brand), whereas the ~250k brand names have no authoritative public list. A brand-only
strip therefore declines rather than guesses -- the safe direction.

Why the output is committed rather than downloaded at runtime
-------------------------------------------------------------
Drishti is offline-first, and a demo machine cannot depend on cdsco.gov.in being reachable.
The generated file is versioned; this script exists so the provenance is reproducible and
`--check` can prove the committed copy matches the source.
"""
from __future__ import annotations

import argparse
import re
import sys
import urllib.request
from pathlib import Path

NLEM_URL = ('https://cdsco.gov.in/opencms/resources/UploadCDSCOWeb/2018/'
            'UploadConsumer/nlem2022.pdf')

# The alphabetical list occupies these pages; the rest of the PDF is the sectioned tables,
# the added/deleted lists and the index. Parsing the numbered alphabetical list is far more
# reliable than the tables, which interleave dosage strengths with names.
ALPHA_PAGES = range(86, 102)
EXPECTED_COUNT = 384  # the published figure -- a mismatch means the PDF changed

REPO = Path(__file__).resolve().parent.parent.parent
OUT_PATH = REPO / 'data' / 'drug_names_nlem2022.txt'

HEADER = """\
# Drug names for the medicine-mode guardrail (app/drug_db.py).
#
# Source: National List of Essential Medicines 2022, Ministry of Health and Family Welfare,
# Government of India, published via CDSCO:
#   {url}
#
# Generated by data/scripts/build_drug_db.py -- do not hand-edit. Re-run that script to
# regenerate, and `--check` to verify this file still matches the source.
#
# {count} names, expanded from the {entries} numbered entries in the PDF's alphabetical list:
# combination entries such as "Zidovudine (A) + Lamivudine (B)" contribute each component,
# and parenthesised synonyms such as "(Mesalazine/Mesalaine)" contribute each alternative.
#
# Generic names only. Indian labelling requires the generic on the pack, and no authoritative
# public list of the ~250k brand names exists -- see this script's docstring.
"""


def fetch_pdf(dest: Path) -> Path:
    if dest.exists():
        print(f'using cached {dest}')
        return dest
    print(f'downloading {NLEM_URL}')
    req = urllib.request.Request(NLEM_URL, headers={'User-Agent': 'Mozilla/5.0'})
    with urllib.request.urlopen(req, timeout=120) as r:  # noqa: S310 -- fixed https URL
        dest.write_bytes(r.read())
    return dest


def extract_entries(pdf_path: Path) -> list[str]:
    """The 384 numbered names from the PDF's alphabetical list, in document order."""
    try:
        from pypdf import PdfReader
    except ImportError:
        raise SystemExit('pypdf is required to parse the PDF:  pip install pypdf')

    reader = PdfReader(str(pdf_path))
    blob = ' '.join((reader.pages[i - 1].extract_text() or '') for i in ALPHA_PAGES)
    blob = blob.replace('Alphabetical List of Medicines in NLEM 2022', ' ')
    blob = re.sub(r'\s+', ' ', blob)

    # Entries look like "127. Domperidone". The lookbehind stops "30:70" inside
    # "Insulin Premix Injection 30:70" from being read as a new entry number.
    parts = re.split(r'(?<!\d)(\d{1,3})\.\s+', blob)
    numbered = {int(parts[i]): parts[i + 1].strip() for i in range(1, len(parts) - 1, 2)}

    # Integrity check: the list must be 1..384 with no gaps. A silent parse failure would
    # otherwise ship a half-empty database, and a guardrail with holes is worse than none --
    # it declines on real medicines while looking like it works.
    missing = [n for n in range(1, EXPECTED_COUNT + 1) if n not in numbered]
    if missing or len(numbered) != EXPECTED_COUNT:
        raise SystemExit(
            f'parsed {len(numbered)} entries, expected {EXPECTED_COUNT}'
            + (f'; missing {missing[:10]}' if missing else '')
            + '\nThe PDF layout probably changed -- re-check ALPHA_PAGES and the regex.'
        )
    return [numbered[n] for n in sorted(numbered)]


def expand(entry: str) -> list[str]:
    """One PDF entry -> every name worth matching against OCR text."""
    names: list[str] = []
    entry = re.sub(r'\s+a\.\s.*$', '', entry)          # drop "a. ... b. ..." sub-items
    entry = entry.replace('[', '(').replace(']', ')')

    head = re.split(r'\s*\(', entry, maxsplit=1)[0].strip()
    if head:
        names.append(head)

    # Components of a combination: "Tenofovir (A) + Lamivudine (B) + Efavirenz (C)".
    # Worth having individually -- a strip often names only one of them.
    names += [c.strip() for c in re.findall(r'([A-Za-z][A-Za-z\-\' ]{2,})\s*\([ABC]\)', entry)]

    # Parenthesised synonyms: "(Mesalazine/Mesalaine)", "(Centchroman)".
    for group in re.findall(r'\(([^()]*)\)', entry):
        if re.fullmatch(r'[ABC]', group.strip()):
            continue
        names += [alt.strip() for alt in group.split('/') if len(alt.strip()) > 3]

    return names


def build_names(entries: list[str]) -> list[str]:
    seen: dict[str, str] = {}
    for entry in entries:
        for name in expand(entry):
            name = re.sub(r'\s+', ' ', name).strip(' .,-')
            if name:
                seen.setdefault(name.lower(), name)
    return sorted(seen.values(), key=str.lower)


def render(names: list[str], entries: list[str]) -> str:
    header = HEADER.format(url=NLEM_URL, count=len(names), entries=len(entries))
    return header + '\n' + '\n'.join(names) + '\n'


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--check', action='store_true',
                        help='verify the committed file matches the source; exit 1 if not')
    parser.add_argument('--pdf', type=Path, default=Path('nlem2022.pdf'),
                        help='where to cache the downloaded PDF')
    args = parser.parse_args()

    entries = extract_entries(fetch_pdf(args.pdf))
    names = build_names(entries)
    rendered = render(names, entries)

    if args.check:
        if not OUT_PATH.exists():
            raise SystemExit(f'{OUT_PATH} does not exist -- run without --check to build it')
        if OUT_PATH.read_text(encoding='utf-8') != rendered:
            raise SystemExit(f'{OUT_PATH} is out of date -- re-run without --check')
        print(f'{OUT_PATH.name} is current: {len(names)} names')
        return

    OUT_PATH.write_text(rendered, encoding='utf-8')
    print(f'wrote {OUT_PATH}  ({len(names)} names from {len(entries)} NLEM entries)')


if __name__ == '__main__':
    sys.exit(main())
